### ISSUE TITLE
Covariance scaling

### ISSUE THREAD

**Issue by jola6897** [saimanoj18/3d-icp-covariance#5]
Hi,

from what I have observed is that indeed the covariance grows if the computed transformation gets worse. But I think the scale is off. I took a Velodyne VLP32 point cloud and shifted it 1.5m in x direction. I used the transformed point cloud as source and raw point cloud as target. The estimate was set to the identity matrix. Therefore the error in x is 1.5m and the remaining errrors are 0. This results in a x variance of 4.24938e-7 which is a standard deviation of just 0.6mm. 

Do you have an idea to bring this more in line with the real expected covariance/standard deviation?

**Comment by saimanoj18** [comment]
Sorry, I do not have idea on this - can you please ask Andrea Censi or other authors who worked on ICP covariance estimation, if expecting such covariance is possible - which really captures the uncertainty of ICP.
